feat: add support for non-interactive configuration and enhance user prompts across scripts

diff --git a/scripts/check b/scripts/check
--- a/scripts/check
+++ b/scripts/check
@@ -1,13 +1,17 @@
 #!/bin/bash
 
-if [[ ! -f ".checked" ]]; then
-  sudo rm -f /tmp/pckid.csv
-  sudo PCKIDRetrievalTool -f /tmp/pckid.csv
+source scripts/helpers/functions
 
-  if [[ -z "$INTEL_API_KEY" ]]; then
-    read -r -e -p "Please provide your Intel API key: " -i "${INTEL_API_KEY}" INTEL_API_KEY
-    export INTEL_API_KEY=${INTEL_API_KEY}
+if [[ ! -f ".checked" ]]; then
+  if [[ $DEBIAN_FRONTEND == "noninteractive" ]]; then
+    echo "PCKIDRetrievalTool can't be run in non-interactive mode. Please run this script in interactive mode."
+    exit 1
+  else
+    sudo rm -f /tmp/pckid.csv
+    sudo PCKIDRetrievalTool -f /tmp/pckid.csv
   fi
+
+  read_intel_api_key
 
   node ./scripts/helpers/check-fmspc.mjs
   touch .checked
